version: "3"

services:
  app:
    container_name: dev-react-docker-image
    image: dev-react-app-first-docker-image
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "5555:8080"
    environment:
      - WATCHPACK_POLLING=true